apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bungee
spec:
  serviceName: bungee
  replicas: 2
  selector:
    matchLabels:
      role: bungee
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: bungee
    spec:
      nodeSelector:
        bungee: 'true'
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    role: bungee
      containers:
        - name: bungee
          image: gcr.io/stratus-181519/minecraft:bungee-master
          imagePullPolicy: Always
          stdin: true
          tty: true
          readinessProbe:
            exec:
              command:
                - ./health.sh
          livenessProbe:
            initialDelaySeconds: 60
            tcpSocket:
              port: 25566
          ports:
            - containerPort: 25566
              name: minecraft
          resources:
            requests:
              cpu: 1000m
              memory: 3Gi
            limits:
              cpu: 2000m
              memory: 3Gi
          envFrom:
            - configMapRef:
                name: minecraft-config
            - configMapRef:
                name: bungee-config
