apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alpha
spec:
  serviceName: alpha
  selector:
    matchLabels:
      role: alpha
  template:
    metadata:
      labels:
        role: alpha
    spec:
      nodeSelector:
        minecraft: 'true'
      containers:
        - name: minecraft
          image: gcr.io/stratus-181519/minecraft:bukkit-master
          imagePullPolicy: Always
          stdin: true
          tty: true
          ports:
            - containerPort: 25565
              name: minecraft
          readinessProbe:
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 15
            exec:
              command:
                - ./health.sh
          livenessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 30
            exec:
              command:
                - ./health.sh
          resources:
            requests:
              cpu: 250m
              memory: 2Gi
            limits:
              cpu: 3000m
              memory: 4Gi
          envFrom:
            - configMapRef:
                name: alpha-config
            - configMapRef:
                name: minecraft-config
          volumeMounts:
            - name: maps
              mountPath: /minecraft/maps:ro
            - name: rotations
              mountPath: /minecraft/rotations:ro
            - name: config
              mountPath: /minecraft/repo/Config:ro
        - name: request
          image: gcr.io/stratus-181519/minecraft:request
          imagePullPolicy: Always
          ports:
            - containerPort: 25555
              name: minecraft
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              memory: 100Mi
          envFrom:
            - configMapRef:
                name: alpha-config
            - configMapRef:
                name: minecraft-config
      volumes:
        - name: maps
          hostPath:
            path: /storage/maps
        - name: rotations
          hostPath:
            path: /storage/data/rotations
        - name: config
          hostPath:
            path: /storage/Config
