
# Use users' display names rather than than their raw username in various messages. Display names are set by other plugins.
use-display-names: true

# Similar to use-display-names, this allows usage of users' display names when looking up players.
lookup-with-display-names: true

# For /time, /weather, and other commands, broadcast change messages to everyone when you change world information with the commands.
broadcast-changes: true

# Disables some features to be compatible with badly-written server wrappers.
crappy-wrapper-compat: true

# When this setting is enabled, CommandBook's commands will be registered AFTER every 
# other plugin's commands. If any other plugin registers a command that conflicts with
# one of CommandBook's commands, the CommandBook command will be accessible with 
# /commandbook:<command>, and the other plugin's command will be accessible 
# with /<command>
low-priority-command-registration: true

# Give operators (set with the Minecraft /op command) all permissions.
op-permissions: false
component-class-dirs:
- component-classes
component-jar-dirs:
- component-jars

# A list of enabled and disabled components. Components in the disabled list 
# will automatically be removed from the enabled list. Fully qualified class names can 
# or aliases (automatically added to the list by CommandBook) can be used as component names.
components:
    disabled:
    - freeze
    - help
    - warps
    - afk
    - homes
    - kits
    - stored-messages
    - spawn-locations
    enabled:
    - bans
    - messaging
    - teleport
    - items
    - midi
    - time
    - name-verification
    - fun
    - debug
    - thor
    - online-list
    - info
    - world
    - player
    - god
    - flight

# Configurations for CommandBook's built-in components are stored here.
# Custom component configurations are stored as individual files in the the config/ folder
component:
    bans:
        message: You have been banned
        broadcast-bans: false
        broadcast-kicks: false
    homes:
        per-world: false
    warps:
        per-world: false
    afk-checker:
        use-movement-event: true
        movement-threshold: 0.04
        sneak-movement-threshold: 0.004
        afk-minutes: 3
        afk-kick-minutes: 60
        afk-general-sleep-ignored: true
        afk-command-sleep-ignored: false
        afk-general-protection: true
        afk-command-protection: false
        npc-compatibility-mode: false
    messaging:
        console-say-format: <`r*Console`w> %s
        broadcast-format: '`B`l[`x`CBroadcast`B`l] `x`c%s'
        pm-color: GRAY
        pm-text-color: RESET
        twitter-style: false
    teleports:
        call-message:
            sender: '`yTeleport request sent.'
            target: '`c**TELEPORT** %cname%`c requests a teleport! Use /bring <name>
                to accept.'
            too-soon: Wait a bit before asking again.
        bring-message:
            sender: '`yPlayer teleported.'
            target: '`yYour teleport request to %cname%`y was accepted.'
            no-perm: That person didn't request a teleport (recently) and you don't have permission to teleport anyone.
        multiworld: false
    inventory:
        item-permissions-only: false
        allowed-items: []
        disllowed-items: []
        default-item-stack-size: 1
    time-control:
        time-lock:
        time-lock-delay: 20
    thor:
        hammer-items:
        - 257
        - 278
        - 285
        - 270
    online-list:
        show-max-players: true
        grouped-names: false
        list-on-join: false
    stored-messages:
        motd: |-
            Hello, `Y%name%`w.
            The time now is `Y%time%`w and you're in world '%world%'.
            `2This is the default CommandBook MOTD! Adjust it in config.yml.
            `2See `bhttp://wiki.sk89q.com/wiki/CommandBook`2 for more configuration information and help!
        rules: |-
            - Be courteous and respect others.
            - Don't use any tools to give you an unfair advantage.
            `2This is the default CommandBook rules text! You can adjust it in config.yml.
    spawn-locations:
        exact-spawn: false
        centered-teleport: false
    god:
        auto-enable: false
    flight:
        auto-enable: false
        check-world-change: true
