apiVersion: v1
kind: ConfigMap
metadata:
  name: official-config
  namespace: tm
data:
  JAVA_OPTS: -Xms512m -Xmx1G
  SERVER_IDS: 59c694f7a2e3a9000100004a,59c6954da2e3a9000100004c,59c695d7c7143300010000be,59c695f7c7143300010000c0,59c6961ac7143300010000c2,59c69684c7143300010000c6,59c696a6c7143300010000c7,59c696c6c7143300010000c8
